name: BDD Playwright (Behave)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install behave playwright python-dotenv
      - run: playwright install --with-deps
      - name: Run Behave
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: "true"
        run: behave -f pretty -f json -o reports/report.json
      - name: Upload artifacts (reports + traces)
        uses: actions/upload-artifact@v4
        with:
          name: behave-${{ matrix.browser }}
          path: reports/**
