name: Pytest (unit/integration)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        env:
          PYTHONPATH: .
          SECRET_KEY: github-actions-secret   # evita depender de .env
        run: |
          pytest --maxfail=1 -q
